services:
  php:
    image: composer:2.8.4
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./:/www
    command: bash -c "composer install && php -S 0.0.0.0:80 -t www"
    ports:
      - "8000:80"
    working_dir: /www
    depends_on:
      postgres:
        condition: service_healthy
  migrations:
    image: composer:2.8.4
    env_file: .env
    volumes:
      - ./:/www
    working_dir: /www
    depends_on:
      postgres:
        condition: service_healthy
    command: bash -c "
      composer install &&
      php bin/console migrations:continue"
  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: app_password
    ports:
      - "6543:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U app_user -d app_db" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: