name: Tests

on:
  push:
  pull_request:

jobs:
  integration-tests:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          coverage: none

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Install dependencies
        run: composer install --no-progress --no-suggest --prefer-dist --no-interaction

      - name: Run integration tests (Nette Tester)
        run: composer tester

  phpstan:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          coverage: none

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Install dependencies
        run: composer install --no-progress --no-suggest --prefer-dist --no-interaction

      - name: Run PHPStan
        run: composer phpstan